###

Get http://localhost:3000/usuarios

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome":"João Pedro",
    "senha":"12345",
    "email":"joao2@example.com"
}

###

PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
    "nome":"pikachu",
    "senha":"12345",
}

###


Delete http://localhost:3000/usuarios/1

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"joao.pedro@example.com",
    "senha":"12345"
}